### ISSUE TITLE
音视频内容替换

### ISSUE THREAD

**Issue by zyaperson** [maxmeng93/auto-study#1]
能否将音视频内容进行替换成三秒的其它视频，不是倍速播放原视频

**Comment by maxmeng93** [comment]
视频看完80%，任务才算完成。再说别人的资源你怎么替换

**Comment by maxmeng93** [comment]
> 能否将音视频内容进行替换成三秒的其它视频，不是倍速播放原视频

视频看完80%，任务才算完成。再说别人的资源你怎么替换
