### ISSUE TITLE
求看为啥被rejected了呢

### ISSUE THREAD

**Issue by 1xiaocainiao** [maxmeng93/auto-study#5]
admin@admindeiMac auto-study-master % yarn start
yarn start
yarn run v1.22.17
$ node ./src/index.js
40000000840 - 国家开放大学学习指南
Unhandled Rejection at: Promise Promise {
  <rejected> TimeoutError: Navigation timeout of 60000 ms exceeded
      at /Users/admin/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
} reason: TimeoutError: Navigation timeout of 60000 ms exceeded
    at /Users/admin/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111

**Comment by 1xiaocainiao** [comment]
不好意思，开了vpn的原因，但是如果有第二页，我需要改哪里获取第二页的课程呢，请指教

**Comment by maxmeng93** [comment]
> 不好意思，开了vpn的原因，但是如果有第二页，我需要改哪里获取第二页的课程呢，请指教

getCourseDetail.js
