### ISSUE TITLE
安装依赖报告

### ISSUE THREAD

**Issue by B3eStCcc** [maxmeng93/auto-study#8]
请问yarn安装依赖puppeteer步骤一直停留怎么解决

**Comment by maxmeng93** [comment]
> 请问yarn安装依赖puppeteer步骤一直停留怎么解决

可能是下载 Chromium 卡住了，可以尝试全局翻墙。或者将 puppeteer 换成 puppeteer-core

**Comment by B3eStCcc** [comment]
感谢，刚刚安装成功了。请问运行yarn start后Chrome自动打开几秒后又关闭是正常现象吗

**Comment by maxmeng93** [comment]
> 感谢，刚刚安装成功了。请问运行yarn start后Chrome自动打开几秒后又关闭是正常现象吗

查看是否有报错，session是否正确设置了

**Comment by B3eStCcc** [comment]
没有任何报错，Chrome打开网址后更像是闪退。
Session我用的是图中
![P2B{@@(}5]QC]~B6AE@~U@4.png](https://user-images.githubusercontent.com/96114791/170913374-79c8b57a-665e-4204-9845-fb9ec95b21ae.png)的一或三字段

我注意到另一个问题，当我复制控制程序弹出的网址并自己键入账号密码时网页会报如下错误![479I4IY_D)L$41B5Q%[{T1R(1).png](https://user-images.githubusercontent.com/96114791/170913626-26303466-cf35-4a52-99b3-5018a32531e6.png)

**Comment by maxmeng93** [comment]
> 没有任何报错，Chrome打开网址后更像是闪退。 Session我用的是图中 ![P2B{@@(}5]QC]~B6AE@~[U@4.png](mailto:U@4.png)](https://user-images.githubusercontent.com/96114791/170913374-79c8b57a-665e-4204-9845-fb9ec95b21ae.png) 的一或三的value字段
> 
> 我注意到另一个问题，当我复制控制程序弹出的网址并自己键入账号密码时网页会报如下错误![479I4IY_D)L$41B5Q%[{T1R(1).png](https://user-images.githubusercontent.com/96114791/170913626-26303466-cf35-4a52-99b3-5018a32531e6.png)

session 不对

**Comment by B3eStCcc** [comment]
感谢提醒，现在能进入课程了，但是进入之后不会自动学习，几秒后自动跳到下个课程，所有课程跳过后直接闪退  ![%[P(_P6YZXJ1KR[V]U%VTAK(1).png](https://user-images.githubusercontent.com/96114791/170928451-0283a43f-e9ae-47b1-8a9b-8c1909757990.png)

**Comment by maxmeng93** [comment]
程序会先把所有课程的详情页都刷一遍，然后取到所有课程的详情数据后才会学习。你的截图正处于取数据阶段。
